version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 Ari.asgi:application"
    volumes:
      - .:/Ari
      - static_volume:/Ari/staticfiles
      - media_volume:/Ari/mediafiles
    ports:
      - "8023:8000"
    depends_on:
      ari_db:
        condition: service_healthy
      redis:
        condition: service_started
      celery_worker:
        condition: service_started
    restart: always

  ari_db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ari_app
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d ari_app" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:alpine
    ports:
      - "6373:6379"
    volumes:
      - redis_data:/data
    restart: always

  celery_worker:
    build: .
    env_file:
      - .env
    command: celery -A Ari worker --loglevel=info
    volumes:
      - .:/Ari
    depends_on:
      - redis
    restart: always

  celery_beat:
    build: .
    env_file:
      - .env
    command: celery -A Ari beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/Ari
    depends_on:
      - redis
      - ari_db
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
