# Generated by Django 5.1.6 on 2025-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='percentages',
            new_name='variants',
        ),
    ]
