# Generated by Django 5.1.6 on 2025-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0003_rename_percentages_product_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
