# Generated by Django 5.1.6 on 2025-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_note',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.IntegerField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='has_intercom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='intercom_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
