# Generated by Django 5.1.6 on 2025-05-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0004_order_additional_note_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
