# Generated by Django 5.1.6 on 2025-05-02 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0006_order_cancel_reason_order_canceled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('goo', 'Customer'), ('pro', 'Courier'), ('system', 'System')], max_length=10, null=True),
        ),
    ]
