# Generated by Django 5.1.6 on 2025-05-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0008_order_assigned_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('en_route_to_store', 'Do‘konga yo‘lda'), ('arrived_at_store', 'Do‘konga yetib keldi'), ('picked_up', 'Yukni oldi'), ('en_route_to_customer', 'Mijozga yo‘lda'), ('delivered', 'Yetkazib berildi')], default='en_route_to_store', max_length=30),
        ),
    ]
