# Generated by Django 5.1.6 on 2025-05-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0009_order_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
