# Generated by Django 5.1.6 on 2025-05-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0010_order_picked_up_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
