# Generated by Django 5.1.6 on 2025-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0011_order_delivery_price_order_weather_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
