# Generated by Django 5.1.6 on 2025-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0012_order_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('en_route_to_store', 'Do‘konga yo‘lda'), ('arrived_at_store', 'Do‘konga yetib keldi'), ('picked_up', 'Yukni oldi'), ('en_route_to_customer', 'Mijozga yo‘lda'), ('arrived_to_customer', 'manziliga yetib keldi'), ('handed_over', 'Mahsulot topshirildi')], default='en_route_to_store', max_length=30),
        ),
    ]
