# Generated by Django 5.1.6 on 2025-05-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
