# Generated by Django 5.1.6 on 2025-06-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0016_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='score',
            new_name='rating',
        ),
    ]
