# Generated by Django 5.1.6 on 2025-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goo', '0021_alter_order_delivery_price_alter_order_item_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='qr_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
