"""
Django settings for Ari project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(yvdl6-bg$z3w3g^tzidu((m_&lk%iuovld4iney5kb6&36v0g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Isntall app
    'channels',
    'django.contrib.gis',
    'rest_framework',
    'rest_framework_gis',
    'modeltranslation',
    'drf_yasg',
    "corsheaders",
    'rest_framework_simplejwt',

    'user',
    'pro',
    'goo',
    'shop',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    # "ari.middleware.BlockAPIMiddleware",  # Yangi middleware qo‘shamiz
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Ari.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ari.wsgi.application'
ASGI_APPLICATION = "Ari.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'ari_app',
        'USER': 'postgres_user',
        'PASSWORD': 'postgres_password',
        'HOST': 'ari_db',
        'PORT': 5432,
    }
}

# # Redis-ni broker sifatida belgilash
CELERY_BROKER_URL = "redis://redis:6379/0"  # dokcer
# # Backend natijalarini saqlash uchun Redis
CELERY_RESULT_BACKEND = "redis://redis:6379/0"


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'ari_app',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'localhost',
#         'PORT': 5432,
#     }
# }
#
# # Redis-ni broker sifatida belgilash
# CELERY_BROKER_URL = 'redis://localhost:6377/0'  # Local
# # Backend natijalarini saqlash uchun Redis
# CELERY_RESULT_BACKEND = "redis://localhost:6377/0"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # "hosts": [("127.0.0.1", 6377)],
            "hosts": [("redis", 6379)],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # "LOCATION": "redis://127.0.0.1:6377/1",  # 6377 - Redis porting
        "LOCATION": "redis://redis:6379/1",  # 6377 - Redis porting
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = f'{BASE_DIR}/mediafiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200 MB (baytlarda)
DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200 MB

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CORS Ruxsatlar
# CORS_ALLOWED_ORIGINS = [
#     "https://ari.uzfati.uz",
#     "http://ari.uzfati.uz",
# ]

# Agar barcha domenlarga ruxsat berish kerak bo‘lsa:
# CORS_ALLOW_ALL_ORIGINS = True  # Tavsiya etilmaydi

# CORS_ALLOW_CREDENTIALS = True  # Cookie va auth tokenlarni ishlatish uchun


# CSRF sozlamalari
CSRF_TRUSTED_ORIGINS = [
    "http://warehouse.bekzodbek-dev.uz",
    "https://warehouse.bekzodbek-dev.uz",
]

CSRF_COOKIE_SECURE = True  # HTTPS orqali xavfsiz cookie'larni ishlatish
CSRF_USE_SESSIONS = True  # CSRF tokenni sessiya orqali saqlash

LANGUAGES = (
    ('uz', 'O‘zbekcha'),
    ('ru', 'Русский'),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = 'uz'

# Tasklar qayerdan yuklanishi kerakligini aniqlash
CELERY_IMPORTS = (
    "shop.tasks",  # Barcha Celery vazifalari joylashgan papkalarni qo‘shing
)
