# Generated by Django 5.1.6 on 2025-03-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='roles',
            new_name='role',
        ),
    ]
