# Generated by Django 5.1.6 on 2025-03-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_roles_shop_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='about_ru',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='about_uz',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='locations_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='locations_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='title_ru',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='title_uz',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='shoprole',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoprole',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
