# Generated by Django 5.1.6 on 2025-03-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_about_ru_shop_about_uz_shop_locations_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='text_ru',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='text_uz',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='title_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='title_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
