# Generated by Django 5.1.6 on 2025-07-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopfeedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopfeedback',
            unique_together=set(),
        ),
    ]
