# Generated by Django 5.1.6 on 2025-05-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_alter_deliverprofile_deliver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverprofile',
            old_name='has_responded',
            new_name='is_busy',
        ),
    ]
