# Generated by Django 5.1.6 on 2025-05-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_rename_has_responded_deliverprofile_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverprofile',
            name='role',
            field=models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike')], default='foot', max_length=4),
        ),
    ]
