# Generated by Django 5.1.6 on 2025-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('foot', 'Piyoda'), ('bike', 'Velosiped')], max_length=10)),
                ('min_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_price', models.PositiveIntegerField(help_text="Minimal narx (so'mda)")),
                ('price_per_km', models.PositiveIntegerField(help_text="1 km uchun narx (so'mda)")),
                ('rain_multiplier', models.FloatField(default=1.3)),
                ('snow_multiplier', models.FloatField(default=1.3)),
                ('thunderstorm_multiplier', models.FloatField(default=1.3)),
                ('drizzle_multiplier', models.FloatField(default=1.1)),
                ('clouds_multiplier', models.FloatField(default=1.1)),
                ('clear_multiplier', models.FloatField(default=1.0)),
            ],
        ),
    ]
